export { default as Home } from './home/Home'
export { default as Favorites } from './favorites/Favorites'
export { default as Reviews } from './reviews/Reviews'
export { default as Basket } from './basket/Basket'
export { default as ProductPage } from './poductPage/ProductPage'
export { default as NotFound } from './notFound/NotFound'